### PR TITLE
Refactor Middleman Blogging for making guides

### LINKED ISSUE #11: Sticky sidebar overflows on mobile
When viewing the API section on a mobile device, the sticky sidebar renders beneath the guide text.

Note: I'll have a crack at submitting a patch for this if I get time in the week

On Chrome Android:

screenshot_2017-10-22-20-58-21

### PR DESCRIPTION
**Pull request by alexcu**
This PR refactors [Middleman Blogging](http://middlemanapp.com/basics/blogging/) into the Guides.

The directory structure has been modified to make the root publication directory `articles`, which encompass `guides`,  `installation` and `contribution`.

To create a guide run:

```
bundle exec middleman article [Name of Article] -t [tag]
```

This will produce a new guide with a timestamp under `articles/guides`. The `[tag]` must be set to an `api_group`, such as the existing `json`, `utilities`, and `database` guides. The basic structure of a guide is a Markdown file that contains the following [frontmatter](https://middlemanapp.com/basics/frontmatter/):

```
---

title: Sample Guide using Middleman Blogging
date: 2017-10-03 06:21 UTC
author: Alex Cummaudo
author_url: http://github.com/alexcu
tags: graphics
summary: |
  This is a summary of the article that should be no more than two 
  to three lines and should embody the gist of the article.
related_funcs:
  - put
  - related
  - function names
  - here
  - like
  - create_window
  - draw_rectangle
  - refresh_screen
  - etc.

---

Begin writing the article here. Note that this is just **markdown**. No need to do a <h1> or # as the template will generate this for you.
```

Additionally, this PR add some minor refactors and enhancements to looks, such as:

- Improvements to overloaded methods:
    Improvements to overloaded methods
- Improvements to guide category/tag pages
    Improvements to guides tag pages
- Improvements to guides flow, adding automatic header and authorship details (with optional author website!)
    Improvements to guides article

Also fixes #11 (thanks @isdampe for reporting this!)

**Still left as WIP:**

- Refactor contribution article on how to write guides using the middleman command

### CODE REVIEW

**Comment by alexcu** [comment]
@jakerenzella It would be good to go through this with you so we can update how contributors (I'm thinking of #8, #10 and #9) can refactor their guides into the new format. Alternatively, we can merge these PRs first, and then merge in #12 and refactor these new guides into the new format.

**Comment by alexcu** [comment]
@jakerenzella @macite Feedback on these changes (i.e., anything that may be now missing) would be great if you get a chance to have a look.

**Comment by jakerenzella** [comment]
@alexcu Will review 👍

**Comment by alexcu** [comment]
Now that this PR has been merged, @isdampe you may want to review the guides you published a while ago and see if you would like to update any authorship details in the new format 😊

As for #9 and #10, @AkshatBajaj  and @drosborn you will need to update the PRs to reflect the new changes (just refer to the new guides for writing blog posts and ensure your post contents are consistent with them 😊). If you no longer want to contribute these blogs, you can close them or we can publish them on your behalf :)

**Comment by isdampe** [comment]
Thanks for the heads up @alexcu I will check it out when I have some spare minutes :)

**Comment by AkshatBajaj** [comment]
Thanks @alexcu I will make changes in the guide.

**Comment by isdampe** [comment]
I've taken a look this morning - the published guides I authored seem to still fit in well, in terms of context.

Good job on the updated contributing guide!

**Pull request merged**
