### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by isdampe**
This PR upgrades both the installation guide index and the general guide index to use an improved "grid layout", in preparation for adding code examples / guides.

screencapture-localhost-4567-guides-installation-1505212659334
screencapture-localhost-4567-guides-installation-1505212651999
screencapture-localhost-4567-guides-1505212638467
screencapture-localhost-4567-guides-1505212623378

### CODE REVIEW

**Comment by alexcu** [comment]
Nice one, this looks awesome now!

**Comment by jakerenzella** [comment]
@alexcu Any ideas for the publishing process? On a pull request basis?

**Comment by alexcu** [comment]
Review code from the PR's branch by creating a new remote for their branch, run the site locally, then test if it's working. Then deploy.

**Comment by alexcu** [comment]
Made live in https://github.com/splashkit/splashkit.io/commit/ec855731ebc22580c43aa51224e89c85c8a50fea

**Comment by alexcu** [comment]
Deployment issues made live in 9c7aac6

**Pull request merged**
